### PR TITLE
Hide broken sidebar images

### PR DESCRIPTION
**Pull request by kendaleiv**
Alternatively, we could display a default image instead.

### CODE REVIEW

**Comment by khalidabuhakmeh** [comment]
Maybe instead of hiding we should show a place holder image.

**Comment by kendaleiv** [comment]
That seems reasonable.

**Comment by hougasian** [comment]
https://en.gravatar.com/site/implement/images/#combine-parameters

While the link above states to add `d=404` to the url string, omitting it yields the default gravatar image - which is better that broken.

**Comment by kendaleiv** [comment]
Note: When the image retrieval is moved to the backend the status code is currently internal to the image retriever classes (it either returns a promise resolving to null or the image): https://github.com/ritterim/star-orgs/pull/55/files#diff-c1e912b0ee4c459987074c8ca5becda0R4

**Pull request closed without merging**
